### ISSUE TITLE
Compilation error: error: unknown type name 'CodeSetInfo'

### ISSUE THREAD

**Issue by 173210** [yifanlu/3ds_injector#1]
```
3ds_injector/source/loader.c: In function 'loader_LoadProcess':
3ds_injector/source/loader.c:200:3: error: unknown type name 'CodeSetInfo'
   CodeSetInfo codesetinfo;
```

Should I install another library to build?

**Comment by Shadowtrance** [comment]
You need makerom built from the latest commit then this should build fine.

**Comment by sykhro** [comment]
Be sure to run the latest ctrulib & makerom. The precompiled version of makerom doesn't include the no-padding flag, so you'll have to compile it yourself

**Comment by yifanlu** [comment]
Your ctrulib version needs to be after this commit https://github.com/smealum/ctrulib/pull/253

**Comment by 173210** [comment]
@yifanlu Thank you for your reply. I'll close this issue.
