### ISSUE TITLE
Region-free does not work for manuals

### ISSUE THREAD

**Issue by dankzegriefer** [yifanlu/3ds_injector#4]
The region-free patch does not apply to manuals

**Comment by urherenow** [comment]
Probably related to DLC? IIRC, NTR's language plugin makes those manuals work. Does it? If so, this issue is actually in line with the DLC one that I opened.

**Comment by dankzegriefer** [comment]
No it isn't. It's unrelated.

**Comment by yifanlu** [comment]
Sorry, can you explain your problem?

**Comment by dankzegriefer** [comment]
The usual text telling to redownload from eShop would appear when trying to open a foreign region manual. But not when loading the game.

**Comment by yifanlu** [comment]
Manuals work for me (japanese game cart + japanese sound app)

**Comment by sykhro** [comment]
Same, manual working fine (tested with 太鼓の達人 どんとかつの時空大冒険)

**Comment by chaoskagami** [comment]
Manuals also work fine for me. Tested on Toshin Toshi, Senran Kagura 2: Shinku, Love Plus, and Bravely Second quickly. Japanese region on a US 3ds. These are carts, but also self-converted CIAs.

Are you running off a CIA from some random site? Perhaps it's just built incorrectly.

**Comment by yifanlu** [comment]
I'll close this for now. Reopen it if you have more info.
